CREATE TABLE IF NOT EXISTS users (
	id serial PRIMARY key,
	name CHAR (70) UNIQUE NOT NULL,
	Username VARCHAR (50) UNIQUE NOT NULL,
	Email VARCHAR (75) UNIQUE NOT NULL,
	Password VARCHAR (25) UNIQUE NOT NULL,
	User_favorites VARCHAR (50),
	Age VARCHAR (3)
);
